added smoothie
keshavbabu/recipes pull request #1
Opened 2024-11-05 02:29 UTC by christianwilkins

![IMG_0913](https://github.com/user-attachments/assets/8055e38d-b7da-46c2-ab68-3fd3dfb8c7b0)

2024-11-05 02:39 UTC, keshavbabu requested changes

2024-11-05 02:39 UTC, keshavbabu commented on smoothie.md
> +smoothie recipe, edit as u like
info section should have stuff like `servings` and `time`

2024-11-05 02:39 UTC, keshavbabu commented on smoothie.md
> +Milk
make all these have a `-` before every item in the list.

2024-11-22 00:50 UTC, christianwilkins commented
review @keshavbabu

2024-11-22 04:02 UTC, keshavbabu approved these changes

2024-11-22 04:02 UTC, merged